- generic [active] [ref=e1]:
  - navigation [ref=e2]:
    - link "Ingenium" [ref=e3] [cursor=pointer]:
      - /url: /
    - link "Projects" [ref=e4] [cursor=pointer]:
      - /url: /projects
    - link "Archive" [ref=e5] [cursor=pointer]:
      - /url: /archive
    - link "Skills" [ref=e6] [cursor=pointer]:
      - /url: /skills
    - link "Learnings" [ref=e7] [cursor=pointer]:
      - /url: /learnings
    - link "Tasks" [ref=e8] [cursor=pointer]:
      - /url: /tasks
    - link "Plugins" [ref=e9] [cursor=pointer]:
      - /url: /plugins
    - link "Agents" [ref=e10] [cursor=pointer]:
      - /url: /agents
    - link "Servers" [ref=e11] [cursor=pointer]:
      - /url: /servers
    - link "Settings" [ref=e12] [cursor=pointer]:
      - /url: /settings
    - link "OpenCode" [ref=e13] [cursor=pointer]:
      - /url: /opencode
  - main [ref=e14]:
    - iframe [ref=e16]:
      
  - alert [ref=e17]