import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
/**
 * Landing page — displays a grid of navigation cards linking to each management section.
 * Each card shows the section name and a brief description.
 */
export default function Home() {
    return (_jsxs("div", { className: "space-y-8", children: [_jsx("h1", { className: "text-3xl font-bold", children: "Ingenium Dashboard" }), _jsx("p", { className: "text-gray-600", children: "Manage your AI agent skill system, learnings, tasks, and MCP servers." }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs(Link, { href: "/projects", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "Projects" }), _jsx("p", { className: "text-sm text-gray-500", children: "Manage projects and their configurations" })] }), _jsxs(Link, { href: "/skills", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "Skills" }), _jsx("p", { className: "text-sm text-gray-500", children: "Browse, search, and edit skills" })] }), _jsxs(Link, { href: "/observations", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "Observations" }), _jsx("p", { className: "text-sm text-gray-500", children: "View observations recorded by agents during interactions" })] }), _jsxs(Link, { href: "/tasks", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "Tasks" }), _jsx("p", { className: "text-sm text-gray-500", children: "Track and manage tasks" })] }), _jsxs(Link, { href: "/plugins", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "Plugins" }), _jsx("p", { className: "text-sm text-gray-500", children: "Enable and disable plugins" })] }), _jsxs(Link, { href: "/agents", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "Agents" }), _jsx("p", { className: "text-sm text-gray-500", children: "Manage AI agents \u2014 create, edit, enable, or delete agent definitions synced to OpenCode" })] }), _jsxs(Link, { href: "/mcp-servers", className: "p-6 bg-white rounded-lg border hover:shadow-md transition-shadow", children: [_jsx("h2", { className: "font-semibold text-lg", children: "MCP" }), _jsx("p", { className: "text-sm text-gray-500", children: "Manage MCP servers and tools" })] })] })] }));
}
