"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/lib/AuthContext";
import { api, type ApiTokenSummary, type SessionDevice } from "@/lib/api";
import StepUpDialog from "@/app/components/auth/StepUpDialog";
import { authInput } from "@/app/components/auth/AuthCard";

const sectionClass = "scroll-mt-6 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--color-text-link)] hover:shadow-md transition-shadow";

export default function AccountPage() {
  const { user, session, refresh } = useAuth();
  const [sessions, setSessions] = useState<SessionDevice[]>([]);
  const [tokens, setTokens] = useState<ApiTokenSummary[]>([]);
  const [stepUp, setStepUp] = useState(false);
  const [afterStepUp, setAfterStepUp] = useState<(() => void) | null>(null);
  const [enrollment, setEnrollment] = useState<{ factorId: string; secret: string } | null>(null);
  const [recovery, setRecovery] = useState<string[]>([]);
  const [tokenValue, setTokenValue] = useState("");
  const load = () => void Promise.all([api.auth.sessions(), api.auth.tokens()]).then(([sessionResult, tokenResult]) => { setSessions(sessionResult.data); setTokens(tokenResult.data); });
  useEffect(load, []);
  const protectedAction = (action: () => void) => { if (session.recentStepUp) action(); else { setAfterStepUp(() => action); setStepUp(true); } };

  return <div className="mx-auto max-w-4xl space-y-6">
    <div><h1 className="text-3xl font-bold">Account and security</h1><p className="text-[var(--color-text-secondary)]">Manage your identity, sign-in methods, sessions, and API tokens.</p></div>
    <nav aria-label="Account sections" className="flex flex-wrap gap-3 text-sm"><a href="#security" className="text-[var(--color-text-link)] hover:underline">Security</a><a href="#sessions" className="text-[var(--color-text-link)] hover:underline">Sessions</a><a href="#api-tokens" className="text-[var(--color-text-link)] hover:underline">API tokens</a></nav>
    <section className={sectionClass}><h2 className="text-lg font-semibold">Account</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-[var(--color-text-muted)]">Name</dt><dd>{user.display_name}</dd></div><div><dt className="text-sm text-[var(--color-text-muted)]">Email</dt><dd className="break-all">{user.email_normalized}</dd></div></dl><PasswordForm protect={protectedAction} /></section>
    <section id="security" tabIndex={-1} className={sectionClass}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Authenticator and recovery</h2><p className="text-sm text-[var(--color-text-secondary)]">{session.mfaEnabled ? "Authenticator protection is enabled." : "Add a time-based authenticator."}</p></div><button className="rounded border border-[var(--color-border)] px-3 py-2" onClick={() => protectedAction(() => { if (session.mfaEnabled) setEnrollment({ factorId: "remove", secret: "" }); else void api.auth.totpEnroll().then((result) => setEnrollment(result.data)); })}>{session.mfaEnabled ? "Remove" : "Set up"}</button></div>{enrollment && <TotpForm enrollment={enrollment} onDone={() => { setEnrollment(null); void refresh(); }} setRecovery={setRecovery} />}{recovery.length > 0 && <div role="status" className="mt-4 rounded bg-[var(--color-warning-bg)] p-4"><p className="font-medium">Save these one-time recovery codes now.</p><ul className="mt-2 grid gap-1 font-mono text-sm sm:grid-cols-2">{recovery.map((code) => <li key={code}>{code}</li>)}</ul><button className="mt-3 rounded border border-[var(--color-border)] px-3 py-2" onClick={() => setRecovery([])}>I saved them</button></div>}</section>
    <section id="sessions" tabIndex={-1} className={sectionClass}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Sessions and devices</h2><button className="rounded border border-[var(--color-border)] px-3 py-2" onClick={() => protectedAction(() => void api.auth.revokeOtherSessions().then(load))}>Revoke other sessions</button></div><ul className="mt-4 divide-y divide-[var(--color-border)]">{sessions.map((item) => <li key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{item.device_label || "Browser session"}{item.id === session.id ? " (current)" : ""}</p><p className="text-xs text-[var(--color-text-muted)]">Last active {new Date(item.last_seen_at).toLocaleString()}</p></div>{!item.revoked_at && item.id !== session.id && <button className="rounded border border-[var(--color-border)] px-3 py-1.5 text-sm" onClick={() => protectedAction(() => void api.auth.revokeSession(item.id).then(load))}>Revoke</button>}</li>)}</ul></section>
    <section id="api-tokens" tabIndex={-1} className={sectionClass}><h2 className="text-lg font-semibold">API tokens</h2><TokenForm onCreate={(input) => protectedAction(() => void api.auth.createToken(input).then(({ data }) => { setTokenValue(data.token ?? ""); load(); }))} />{tokenValue && <div role="status" className="mt-4 rounded bg-[var(--color-warning-bg)] p-4"><p className="font-medium">Copy this token now. It will not be shown again.</p><code className="mt-2 block break-all select-all">{tokenValue}</code><button className="mt-3 rounded border border-[var(--color-border)] px-3 py-2" onClick={() => setTokenValue("")}>I copied it</button></div>}<ul className="mt-4 divide-y divide-[var(--color-border)]">{tokens.map((token) => <li key={token.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{token.name}</p><p className="text-xs text-[var(--color-text-muted)]">{token.tokenPrefix} · expires {new Date(token.expiresAt).toLocaleDateString()}</p></div>{!token.revokedAt && <button className="rounded border border-[var(--color-border)] px-3 py-1.5 text-sm" onClick={() => protectedAction(() => void api.auth.revokeToken(token.id).then(load))}>Revoke</button>}</li>)}</ul></section>
    <StepUpDialog open={stepUp} onClose={() => { setStepUp(false); setAfterStepUp(null); }} onComplete={() => { setStepUp(false); void refresh(); afterStepUp?.(); setAfterStepUp(null); }} />
  </div>;
}

function PasswordForm({ protect }: { protect: (action: () => void) => void }) { const [current, setCurrent] = useState(""); const [password, setPassword] = useState(""); const [done, setDone] = useState(false); return <form className="mt-6 grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); protect(() => void api.auth.changePassword(current, password).then(() => { setCurrent(""); setPassword(""); setDone(true); })); }}><div><label htmlFor="current-password" className="text-sm font-medium">Current password</label><input id="current-password" type="password" autoComplete="current-password" className={authInput} value={current} onChange={(event) => setCurrent(event.target.value)} required /></div><div><label htmlFor="changed-password" className="text-sm font-medium">New password</label><input id="changed-password" type="password" minLength={12} autoComplete="new-password" className={authInput} value={password} onChange={(event) => setPassword(event.target.value)} required /></div><button className="rounded bg-blue-600 px-4 py-2 text-white sm:col-span-2">Change password</button>{done && <p role="status" className="text-sm text-[var(--color-success-text)]">Password changed.</p>}</form>; }
function TotpForm({ enrollment, onDone, setRecovery }: { enrollment: { factorId: string; secret: string }; onDone: () => void; setRecovery: (codes: string[]) => void }) { const [code, setCode] = useState(""); return <form className="mt-4 space-y-3" onSubmit={async (event) => { event.preventDefault(); if (enrollment.factorId === "remove") await api.auth.totpRemove(code); else { const result = await api.auth.totpConfirm(enrollment.factorId, code); setRecovery(result.data.recoveryCodes); } setCode(""); onDone(); }}>{enrollment.secret && <p className="break-all rounded bg-[var(--color-surface-muted)] p-3 font-mono text-sm">Secret: {enrollment.secret}</p>}<label className="block text-sm font-medium" htmlFor="totp-code">{enrollment.factorId === "remove" ? "Authenticator or recovery code" : "Six-digit authenticator code"}</label><input id="totp-code" className={authInput} autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} required /><button className="rounded bg-blue-600 px-4 py-2 text-white">Confirm</button></form>; }
function TokenForm({ onCreate }: { onCreate: (input: { name: string; scopes: string[]; expiresAt: string }) => void }) { const [name, setName] = useState(""); const [scope, setScope] = useState("projects:read"); return <form className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={(event) => { event.preventDefault(); onCreate({ name, scopes: [scope], expiresAt: new Date(Date.now() + 30 * 86_400_000).toISOString() }); setName(""); }}><div><label htmlFor="token-name" className="text-sm font-medium">Token name</label><input id="token-name" className={authInput} value={name} onChange={(event) => setName(event.target.value)} required /></div><div><label htmlFor="token-scope" className="text-sm font-medium">Scope</label><input id="token-scope" className={authInput} value={scope} onChange={(event) => setScope(event.target.value)} required /></div><button className="self-end rounded bg-blue-600 px-4 py-2 text-white">Create token</button></form>; }
