server {
    listen 3000;
    listen [::]:3000;
    server_name opencode.localhost;
    include /app/nginx/runtime-alias-unavailable-location.conf;
}

server {
    listen 3000;
    listen [::]:3000;
    server_name cli.localhost;
    include /app/nginx/runtime-alias-unavailable-location.conf;
}

server {
    listen 3000;
    listen [::]:3000;
    server_name vscode.localhost;
    include /app/nginx/runtime-alias-unavailable-location.conf;
}
